# entry(main)
stages:
  - install
  - cache
  - deploy



InstallNode:
  stage: install
  image: node:latest

cache:
  stage: cache
  paths:
    - node_modules

pages:
  stage: deploy
  script:
  # note: this must global
  - npm i -g tiddlywiki
  - tiddlywiki --build index
  - rm -rf public
  - mv output/ public

  # test
  - cd ..
  - ls
  - cd ..
  - ls
  artifacts:
    paths:
    - public
  only:
  - main
