# entry(main)
#stages:
  #- install
  #- cache
  #- deploy



#InstallNode:
  #stage: install
image: node:latest


#Cache:
  #stage: cache
cache:
  paths:
  - node_modules


pages:
  stage: deploy
  script:
  # note: this must global
  - npm i -D tiddlywiki
  - npm i -g tiddlywiki
  - ls
  - tiddlywiki --build index
  - rm -rf public
  - mv output/ public
  - ls /lib/node_modules

  artifacts:
    paths:
    - public
  only:
  - main
