image: node:latest

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
  - npm i tiddlywiki
  - tiddlywiki --build index
  - rm -rf public/*
  - cp output/* public
  artifacts:
    paths:
    - public
  only:
  - main
