image: node:latest

stages:
  - deploy

pages:
  stage: deploy
  script:
  # yarn install to fix cache first
  - yarn install
  - yarn devbuild && yarn copy && yarn copyg

  artifacts:
    paths:
    - public
    expire_in: 7 days
  only:
  #- main
    - tags

cache:
  paths:
  - node_modules
