cache:
  paths:
    - node_modules

image: node:latest

#building:
  #stage: build
  #image: node:latest


pages:
  stage: deploy
  script:
  # note: this must global
  - npm i -g tiddlywiki
  - ls
  - tiddlywiki --build index
  - rm -rf public/*
  - cp output/* public
  artifacts:
    paths:
    - public
  only:
  - main
