image: node:latest

pages:
  only:
    #- tags
    - main

  script:
    - yarn build@vercel

  artifacts:
    #enabled: false
    paths:
      - public
    expire_in: 20 minutes


  cache:
    paths:
      - node_modules
