image: node:latest

stages:
  - deploy

pages:
  stage: deploy
  script:
  # yarn install to fix cache first
  - yarn install
  - yarn clean-pub
  - yarn build
  - yarn deploy
  - yarn version-tw

  artifacts:
    paths:
    - public
  only:
  - main

cache:
  paths:
  - node_modules

