image: node:latest

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
  - npm i -g tiddlywiki
  - tiddlywiki --build index
  - rm -rf public/*
  - ls output
  #- mv output/index.html public/index.html
  artifacts:
    paths:
    - public
  only:
  - main
