stages:
  - deploy

.deploy:
  image: node:latest
  stage: deploy
  script:
    - yarn install
    - yarn clean && yarn devbuild && yarn copy

  artifacts:
    #enabled: false
    paths:
      - public
    expire_in: 20 minutes

  only:
    - main

  cache:
    paths:
      - node_modules
