building:
  image: node:latest
  stage: build

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
  - npm i -g tiddlywiki
  - tiddlywiki --build index
  - rm -rf public/*
  - ls output
  - mv output/* public
  - ls public
  artifacts:
    paths:
    - public
  only:
  - main
