image: node:latest

stages:
  - deploy

test:
  stage: hello
  script:
  - echo "This is a echo statement."

pages:
  stage: deploy
  script:
  # yarn install to fix cache first
  - yarn install
  - yarn devbuildp && yarn copy

  artifacts:
    #enabled: false
    paths:
    - public
    expire_in: 20 minutes

  only:
    #- tags
    - null

cache:
  paths:
  - node_modules
