stages:
  - gitlabPages

gitlabPages:
  image: node:latest
  stage: deploy
  script:
    - yarn build@vercel

  artifacts:
    #enabled: false
    paths:
      - public
    expire_in: 20 minutes

  only:
    - tags

  cache:
    paths:
      - node_modules
