image:  node:latest

pages:
  script:
    - npm install tiddlywiki -g
    - tiddlywiki --build index
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
    #key: project
  #rules:
    #- if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
