deploy:
  image: node:latest
  stage: deploy
  script:
    - yarn build@vercel

  artifacts:
    #enabled: false
    paths:
      - public
    expire_in: 20 minutes

pages:
  - deploy

stages:
  only:
    #- tags
    - tw6

  cache:
    paths:
      - node_modules
