image: node:latest

cache:
  paths:
  - node_modules

pages:
  stage: deploy
  script:
  - yarn clean-pub
  - yarn build
  - yarn deploy
  - yarn version-tw

  artifacts:
    paths:
    - public
  only:
  - main
