#building:
  #image: node:latest
  #stage: build

image: node:latest

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
  - npm i -g tiddlywiki
  - tiddlywiki --build index
  - rm -rf public/*
  #- ls output
  - rm public -rf
  #- mkdir public
  - cp output/* public
  #- ls public
  artifacts:
    paths:
    - public
  only:
  - main
