#image: node:latest

stages:
  - test
  - deploy

#pages:

test:
  script:
    echo "THIS"

deploy:
  stage: deploy
  image: node:latest
  script:
  # yarn install to fix cache first
  - yarn install
  - yarn clean && yarn devbuild && yarn copy

  artifacts:
    #enabled: false
    paths:
    - public
    expire_in: 20 minutes

  only:
    - main
    #- tags
  cache:
   paths:
   - node_modules
