stages:
  - test
  - Deploy GitlabPages

.test:
  script:
    echo Hello

Deploy GitlabPages:
  image: node:latest
  stage: deploy
  script:
    - yarn build@vercel

  artifacts:
    #enabled: false
    paths:
      - public
    expire_in: 20 minutes

  only:
    - tags

  cache:
    paths:
      - node_modules
