image: node:latest

stages:
  - deploy

pages:
  stage: deploy
  script:
  # yarn install to fix cache first
  - yarn install
  - yarn devbuild && yarn copy && yarn copyg

  artifacts:
    paths:
    - public
    expire_in: 2 minutes
  only:
    - tags
  #- main

cache:
  paths:
  - node_modules
