image: node:latest

stages:
  - deploy

pages:
  stage: deploy
  script:
  # yarn install to fix cache first
  - yarn install
  - yarn build && yarn copy

  artifacts:
    paths:
    - public
    #expire_in: 1 day
    expire_in: 2 mins
    #expire_in: never
  only:
  #- main
    - tags

cache:
  paths:
  - node_modules
