image: node:latest

stages:
  - deploy

pages:
  stage: deploy
  script:
  # yarn install to fix cache first
  - yarn install
  - yarn build

  artifacts:
    paths:
    - public
    #expire_in: 1 days
    expire_in: 1 mins
    #expire_in: never
  only:
  - main
    #- tags

cache:
  paths:
  - node_modules
