name: Deploy Tiddlywiki To Github Pages

on:
  push:
    branches:
      - main
    #tags:
      #- '*'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          #key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependency
        run: yarn install
      - name: Build
        run: yarn build@vercel

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
